# Generated by Django 5.0.6 on 2024-07-26 20:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
