# Generated by Django 5.0.6 on 2024-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuilauserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
